# Generated by Django 3.0.4 on 2020-03-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
